name: testes e cobertura - react

on:
  push:
    branches: [main]

jobs:
  test:
    name: executar testes em ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: checkout do código
        uses: actions/checkout@v3

      - name: configurar node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: instalar dependências
        run: npm install

      - name: rodar testes com cobertura
        run: npm test

      # - name: enviar cobertura para codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: ./coverage/lcov.info
