name: testes e cobertura - react

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  frontend-test:
    name: executar testes em ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: checkout do código
        uses: actions/checkout@v4

      - name: configurar node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: instalar dependências
        working-directory: ./frontend
        run: npm install

      - name: rodar testes com cobertura
        working-directory: ./frontend
        run: npm test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./frontend/coverage/lcov.info
          working-directory: ./

  cypress-e2e:
    name: Cypress E2E em ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: checkout do código
        uses: actions/checkout@v4

      - name: configurar node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: instalar dependências
        working-directory: ./frontend
        run: npm install

      - name: instalar backend (se necessário)
        working-directory: ./backend
        run: npm install

      - name: iniciar backend
        working-directory: ./backend
        run: npm start &
      
      - name: esperar backend subir
        run: npx wait-on http://localhost:3001

      - name: rodar Cypress
        working-directory: ./frontend
        run: npx cypress run
